<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=windows-1252">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="OpenOffice.org 2.3  (Win32)">
	<META NAME="CREATED" CONTENT="20080531;18130520">
	<META NAME="CHANGED" CONTENT="20080601;16394183">
</HEAD>
<BODY LANG="fr-FR" DIR="LTR">
<TABLE WIDTH=100% BORDER=1 CELLPADDING=4 CELLSPACING=3 STYLE="page-break-before: always; page-break-inside: avoid">
	<COL WIDTH=36*>
	<COL WIDTH=166*>
	<COL WIDTH=54*>
	<TR VALIGN=TOP>
		<TD ROWSPAN=2 WIDTH=14%>
			<P>Searchbox</P>
			<P>Expressions</P>
			<P>Sons</P>
			<P>Images</P>
			<P>Videos</P>
			<P>Textes</P>
			<P>Affirmations</P>
			<P>Gouts</P>
		</TD>
		<TD COLSPAN=2 WIDTH=86%>
			<P ALIGN=CENTER>Questions</P>
			<P ALIGN=RIGHT>Membres</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD WIDTH=65%>
			<P>Liste questions</P>
		</TD>
		<TD ROWSPAN=2 WIDTH=21%>
			<P>Liste membres</P>
			<P ALIGN=RIGHT>Mes affinites (Nuage Points)</P>
		</TD>
	</TR>
	<TR VALIGN=TOP>
		<TD COLSPAN=2 WIDTH=79%>
			<P>Avatar &ndash; mon compte</P>
			<P ALIGN=CENTER>Panel Reponse</P>
		</TD>
	</TR>
</TABLE>
<P><BR><BR>
</P>
</BODY>
</HTML>